# Properties File will take precidance over yml

# Server
server:
  port: 8082

spring:
  # # H2 Database
  # h2:
  #     console:
  #         enabled: true

  # datasource:
  #     url: jdbc:h2:mem:dcbapp
  #     driverClassName: org.h2.Driver
  #     username: sa
  #     password: password

  # jpa:
  #     database-platform: org.hibernate.dialect.H2Dialect

  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Logging
logging:
  level:
    root: INFO
  pattern:
    console: '{"timeStamp":"%d{yyyy-MM-dd HH:mm:ss}", "level": "%p", "logger": "%logger{36}", "message": "%msg"}%n'

# Custom Config
welcome:
  message: Spring Boot Application Version 1
